# Generated by Django 5.2.3 on 2025-06-17 07:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Student Email')),
                ('semester', models.CharField(blank=True, choices=[('SEM_ONE', 'Semester One'), ('SEM_TWO', 'Semester Two'), ('SEM_THREE', 'Semester Three'), ('SEM_FOUR', 'Semester Four'), ('SEM_FIVE', 'Semester Five'), ('SEM_SIX', 'Semester Six'), ('SEM_SEVEN', 'Semester Seven'), ('SEM_EIGHT', 'Semester Eight')], default='N/A', max_length=20, null=True)),
                ('phone_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Teacher Full Name')),
                ('email', models.CharField(max_length=100, null=True, unique=True, verbose_name='Teacher Email')),
                ('department', models.CharField(blank=True, choices=[('BCA', 'Bachelor of Computer Application'), ('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=5, null=True)),
                ('phone_no', models.IntegerField()),
                ('join_date', models.DateField(default='Join Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Material title')),
                ('category', models.CharField(choices=[('SLIDE', 'Chapter slide'), ('TEXT_BOOK', 'A text book'), ('REFERENCE_BOOK', 'A reference book'), ('OLD_QUESTION', 'Previous board exam question'), ('AUDIO_BOOK', 'An audio book')], max_length=30, verbose_name='category')),
                ('description', models.CharField(max_length=255, verbose_name='material description')),
                ('subject', models.CharField(choices=[('BEI001', 'Signals and Systems'), ('BEI002', 'Instrumentation'), ('BEI003', 'Electromagnetics'), ('BEI004', 'Numerical methods'), ('BEI005', 'Discrete Structures')], default='N/A', max_length=20, verbose_name=' Materials ubject')),
                ('material_file', models.FileField(upload_to='material/', verbose_name='seletct file')),
                ('upload_file', models.DateTimeField(default=datetime.datetime(2025, 6, 17, 13, 35, 24, 941817), verbose_name='upload date')),
                ('teacher', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'verbose_name': 'materials',
                'verbose_name_plural': 'materials',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignment Title')),
                ('start_date', models.DateField(default='Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(default='End Date', verbose_name='End Date')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='assignments/questions/', verbose_name='Select Assignment File')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Assignment Question')),
                ('remark', models.CharField(max_length=100, verbose_name='Assignment Details')),
                ('full_mark', models.FloatField()),
                ('subject', models.CharField(choices=[('BEI001', 'Signals and Systems'), ('BEI002', 'Instrumentation'), ('BEI003', 'Electromagnetics'), ('BEI004', 'Numerical methods'), ('BEI005', 'Discrete Structures')], default='N/A', max_length=20, verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['-title'],
            },
        ),
    ]
