# Generated by Django 5.2.3 on 2025-06-19 07:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-title'], 'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='material',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_subject',
            field=models.CharField(choices=[('BEI001', 'Software Engineering'), ('BEI002', 'System Analysis and Design'), ('BEI003', 'Operating System'), ('BEI004', 'Object Oriented Programming'), ('BEI005', 'Electornics & Instrumentation')], default='N/A', max_length=20, verbose_name='Assignment Subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_subject',
            field=models.CharField(choices=[('BEI001', 'Software Engineering'), ('BEI002', 'System Analysis and Design'), ('BEI003', 'Operating System'), ('BEI004', 'Object Oriented Programming'), ('BEI005', 'Electornics & Instrumentation')], default='N/A', max_length=20, verbose_name='Material Subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('SLIDE', 'Chapter Slide'), ('TEXT_BOOK', 'A text book'), ('REFERENCE_BOOK', 'A reference book'), ('OLD_QUESTION', 'Previous board exam question'), ('AUDIO_BOOK', 'An audio book')], max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(upload_to='material/', verbose_name='Select file'),
        ),
        migrations.AlterField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Material Title'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
    ]
